apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-receiver
  name: udaconnect-location-receiver
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30021
  selector:
    service: udaconnect-location-receiver
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-receiver
  name: udaconnect-location-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-receiver
  template:
    metadata:
      labels:
        service: udaconnect-location-receiver
    spec:
      containers:
      - image: alanbrant/udaconnect-location-receiver:latest
        name: udaconnect-location-receiver
        imagePullPolicy: Always
      restartPolicy: Always
